export const sites = {
  "channel5.com": {
    local: "http://local.channel5.com:3000",
    stage: "https://stage-www-channel5-com.webplex.vmn.io",
    prod: "https://prod-www-channel5-com.webplex.vmn.io",
  },
  "bet.plus": {
    local: "http://local.bet.plus:3000",
    stage: "https://stage-www-bet-plus.webplex.vmn.io",
    prod: "https://bet.plus",
  },
  "smithsonianchannel.com": {
    local: "http://local.smithsonianchannel.com:3000",
    stage: "https://stage-www-smithsonianchannel-com.webplex.vmn.io",
    prod: "https://www.smithsonianchannel.com",
  },
};

export const rawSites = [
  "bet.plus",
  "bet.com",
  "comedycentral.co.uk",
  "comedycentral.com.br",
  "comedycentral.com.ro",
  "comedycentral.es",
  "comedycentral.fr",
  "comedycentral.hu",
  "comedycentral.it",
  "comedycentral.la",
  "comedycentral.pl",
  "comedycentral.tv",
  "comedycentralafrica.com",
  "comedycentralarabia.com",
  "comedycentralasia.com",
  "kca.mundonick.com.br",
  "kca.mundonick.com",
  "kca.nick.com.pl",
  "kca.nick.de",
  "kca.nickelodeon.be",
  "kca.nickelodeon.dk",
  "kca.nickelodeon.es",
  "kca.nickelodeon.fr",
  "kca.nickelodeon.hu",
  "kca.nickelodeon.nl",
  "kca.nickelodeon.no",
  "kca.nickelodeon.pt",
  "kca.nickelodeon.ro",
  "kca.nickelodeon.ru",
  "kca.nickelodeon.se",
  "kca.nicktv.it",
  "kcamexico.com",
  "kidschoiceawardsmexico.mundonick.com",
  "la.nickjr.tv",
  "meuspremiosnick.com.br",
  "mtv-v1.com",
  "mtv.co.il",
  "mtv.co.za",
  "mtv.com.au",
  "mtv.com.br",
  "mtv.com",
  "mtv.de",
  "mtv.es",
  "mtv.it",
  "mtv.nl",
  "mtv.pl",
  "mtvasia.com",
  "mtvbase.com",
  "mtvema.com",
  "mtvjapan.com",
  "mtvla.com",
  "nick-video.com",
  "nick.com.pl",
  "www.nick.de",
  "nickatnite.com",
  "nickelodeon.com.br",
  "www.nickelodeon.es",
  "nickelodeon.fr",
  "nickelodeon.hu",
  "nickelodeon.la",
  "nickelodeon.nl",
  "nickelodeon.pt",
  "nickelodeonafrica.com",
  "nickelodeonjunior.fr",
  "nickjr.co.uk",
  "nickjr.com.au",
  "nickjr.com.br",
  "nickjr.com.pl",
  "nickjr.de",
  "nickjr.dk",
  "nickjr.es",
  "nickjr.it",
  "nickjr.nl",
  "nickjr.tv",
  "paramountchannel.com.br",
  "paramountnetwork.com",
  "paramountnetwork.es",
  "paramountnetwork.it",
  "slimefest.it",
  "www.smithsonianchannel.co.uk",
  "www.smithsonianchannel.com",
  "www.smithsonianchannellatam.com",
  "southpark.cc.com",
  "southpark.de",
  "southpark.lat",
  "southparkstudios.co.uk",
  "southparkstudios.com.br",
  "southparkstudios.com",
  "southparkstudios.nu",
  "supertv.it",
  "tvland.com",
  "vh1.com",
  "vidcon.com",
];
